FROM node:20

WORKDIR /app

# Solo copiamos los package.json para instalar dependencias
COPY package*.json ./
RUN npm install

# No copiamos el resto, porque será montado con el volumen

EXPOSE 4321

CMD ["npm", "run", "dev", "--host"]
