export const Courses = [
    {
        id: 1,
        title: "INTRODUCCIÓN: ¿QUÉ ES LA PROGRAMACIÓN? PENSAMIENTO COMPUTACIONAL",
        available: true,
        description:
            "Aprende a pensar como programador y a resolver problemas paso a paso con el poder del pensamiento computacional, incluso antes de escribir código.",
        videoUrl: "https://www.youtube.com/watch?v=RDLEo5mlTOI",
        posterUrl: "/images/courses/course-1.jpg",
        categories: ["Introducción", "Pensamiento Computacional", "Programación"],
    },
    {
        id: 2,
        title: "LÓGICA DE PROCESOS: ENTRADA, PROCESAMIENTO Y SALIDA",
        available: true,
        description: "Descubre cómo aplicar la lógica de procesos —entrada, procesamiento y salida— para organizar ideas, resolver problemas y pensar como programador en cualquier situación.",
        videoUrl: "https://www.youtube.com/watch?v=q6pk7kH2U2w",
        posterUrl: "/images/courses/course-2.jpg",
        categories: [],
    },
    {
        id: 3,
        title: "ALGORITMOS: DEFINICIÓN, ESTRUCTURA Y EJEMPLOS",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-3.jpg",
        categories: [],
    },
    {
        id: 4,
        title: "DIAGRAMAS DE FLUJO: SÍMBOLOS, DISEÑO Y LECTURA",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-4.jpg",
        categories: [],
    },
    {
        id: 5,
        title: "DIAGRAMAS DE FLUJO: PRÁCTICA GUIADA + EJERCICIOS",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-5.jpg",
        categories: [],
    },
    {
        id: 6,
        title: "PSEUDOCÓDIGO: REGLAS, SINTAXIS Y TRADUCCIÓN DESDE EL DIAGRAMA",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-6.jpg",
        categories: [],
    },
    {
        id: 7,
        title: "PSEUDOCÓDIGO: RESOLUCIÓN DE PROBLEMAS COMUNES",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-7.jpg",
        categories: [],
    },
    {
        id: 8,
        title: "FUNDAMENTOS DE PYTHON: VARIABLES, TIPOS DE DATOS, OPERADORES",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-8.jpg",
        categories: [],
    },
    {
        id: 9,
        title: "CONTROL DE FLUJO: CONDICIONALES Y CICLOS EN PYTHON",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-9.jpg",
        categories: [],
    },
    {
        id: 10,
        title: "ESTRUCTURAS DE DATOS: LISTAS, DICCIONARIOS, TUPLAS",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-10.jpg",
        categories: [],
    },
    {
        id: 11,
        title: "FUNCIONES EN PYTHON + MINI PROYECTO GUIADO",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-11.jpg",
        categories: [],
    },
    {
        id: 12,
        title: "PROYECTO FINAL: DESARROLLAR UNA APP SIMPLE RESOLVIENDO UN PROBLEMA REAL",
        available: false,
        description: "Disponible próximamente.",
        videoUrl: "",
        posterUrl: "/images/courses/course-12.jpg",
        categories: [],
    },
];
